#include <iostream>
#include <string>
using namespace std;
#define mainUwU main
#define cowwen ;
#define vowd void
#define stdOwO std
#define pwint std::cout << 
#define bwaket {
#define cwosebwaket }
#define retuwn return
#define pawenthesis (
#define cwosepawenthesis )
#define integew int
#define stwing std::string
#define chaw char
#define pointew *
#define stwuct struct
#define cwass class
#define pubwic public
#define fuwwcowwent :
#define pwivate private
#define namespawe namespace
#define uswing using
#define ihavestds std
#define equwals =
#define pwus +
#define pwuspwus ++
#define minuwsminuws --
#define bweak break
#define minuws -
#define fow for
#define autow auto
#define endwine endl
#define inpwut std::cin
#define dwot .
#define ifw if
#define awto auto
#define ewse else
#define twue true
#define fawse false
#define twy try
#define cawtch catch
#define thwow throw
#define conwt const
#define vewctor vector
#define continueUwU continue
#define defauwt default
#define doWoop do
#define whiwe while
#define swiwtch switch
#define caseUwU case
#define doubwe double
#define enuwm enum
#define extewn extern
#define fwoat float
#define gowto goto
#define sizeofUwU sizeof
#define wongOwO long
#define registew register
#define showt short
#define signeduwu signed
#define statwic static
#define typewdef typedef
#define unionUwU union
#define vowatile volatile
